[alias]
xtask = "run --package xtask --"

# Platform-specific linker configuration
# Use system linker on macOS since lld doesn't support macOS platform
# Note: Don't override linker for crypto crates like 'ring' as it causes constant recompilation
[target.aarch64-apple-darwin]
# Let Cargo use the default linker for better compatibility with native code crates
# rustflags = ["-C", "linker=/usr/bin/ld"]

[target.x86_64-apple-darwin] 
# Let Cargo use the default linker for better compatibility with native code crates
# rustflags = ["-C", "linker=/usr/bin/ld"]

# Linux: Use lld for faster builds (now installed in CI)
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

# Windows: Use system linker with debug info disabled for faster builds
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "link-arg=/DEBUG:NONE"]

[target.x86_64-pc-windows-gnu]
rustflags = []

[target.wasm32-unknown-unknown]
rustflags = [
    "-C", "target-feature=+bulk-memory,+mutable-globals",
    "--cfg", "getrandom_backend=\"wasm_js\"",
]

# Web-specific configuration
[unstable]
host-config = true

# WASM-specific settings for getrandom
[target.wasm32-unknown-unknown.env]
RUST_LOG = "info"
