[package]
name = "iotcraft-dekstop-client"
version = "0.1.0"
edition = "2024"
default-run = "iotcraft-dekstop-client"

[dependencies]
bevy = { version = "0.16.1", features = ["webp"] }
bevy_console = "0.14.1"
clap = { version = "4.5", features = ["derive"] }
rumqttc = "0.24.0"
rumqttd = "0.19.0"
tokio = { version = "1.47", features = ["rt-multi-thread", "macros", "fs", "net"] }
tracing = "0.1"
tracing-subscriber = "0.3"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
dirs = "6.0"
whoami = "1.5"
rand = "0.9"
hex = "0.4"
fluent = "0.17.0"
fluent-bundle = "0.16.0"
fluent-syntax = "0.12.0"
unic-langid = "0.9.6"
avian3d = "0.3.1"
# MCP (Model Context Protocol) support
tokio-util = { version = "0.7", features = ["codec"] }
futures = "0.3"
anyhow = "1.0"
uuid = { version = "1.0", features = ["v4"] }
bytes = "1.0"
# HTTP server support for mcp-remote
axum = "0.8"
tower = "0.5"
tower-http = { version = "0.6", features = ["cors"] }
# Async channels for Bevy-compatible communication
async-channel = "2.5"
# Performance optimization dependencies
rayon = "1.8" # Parallel processing
bytemuck = { version = "1.16", features = ["derive"] } # GPU data alignment
tempfile = "3.8" # For testing async file operations
