[package]
name = "iotcraft-dekstop-client"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.1"
bevy_console = "0.14.1"
clap = { version = "4.0", features = ["derive"] }
rumqttc = "0.24.0"
rumqttd = "0.19.0"
tokio = "1.45.1"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
log = "0.4.27"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
