# ESP32-S3
[target.xtensa-esp32s3-none-elf]
#runner = "probe-rs run --chip=esp32s3"
runner = "espflash flash --monitor"

# ESP32-C3
[target.riscv32imc-unknown-none-elf]
#runner = "probe-rs run --chip=esp32c6"
runner = "espflash flash --monitor"

# ESP32-C6
[target.riscv32imac-unknown-none-elf]
#runner = "probe-rs run --chip=esp32c6"
runner = "espflash flash --monitor --partition-table partitions.csv"

[env]
DEFMT_LOG="info"
ESP_LOG="INFO"

[build]
# ESP32-S3
#target = "xtensa-esp32s3-none-elf"
# ESP32-C3
#target = "riscv32imc-unknown-none-elf"
# ESP32-C6
rustflags = [
    # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
    # NOTE: May negatively impact performance of produced code
    "-C", "force-frame-pointers",
]
target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = ["alloc", "core"]
