name: Desktop Client Tests

on:
  push:
    paths:
      - 'desktop-client/**'
      - '.github/workflows/desktop-client-tests.yml'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for running the workflow'
        required: false
        default: 'Manual test run'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Linux dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          pkg-config \
          libx11-dev \
          libasound2-dev \
          libudev-dev \
          libxkbcommon-x11-0 \
          libwayland-dev \
          libxrandr-dev \
          libxcursor-dev \
          libxi-dev \
          libxinerama-dev \
          libgl1-mesa-dev \
          libglu1-mesa-dev

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
        
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: desktop-client
        
    #- name: Check formatting
    #  run: |
    #    cd desktop-client
    #    cargo fmt --all -- --check
        
    #- name: Run clippy
    #  run: |
    #    cd desktop-client
    #    cargo clippy --all-targets --all-features -- -D warnings
        
    - name: Run unit tests
      run: |
        cd desktop-client
        cargo test
        
    - name: Check if build works
      run: |
        cd desktop-client
        cargo check --all-targets --all-features
